{{- if eq .Release.Namespace "dc0a4a-dev" }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: dc0a4a-dev
  generateName: maintain-crunchy-devs-
  labels:
    DataClass: "Low"
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 86400 # 1 day
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: maintain-crunchy-devs
          image: quay.io/fedora/postgresql-16
          env:
            - name: DELETE_ID
              value: "{{ .Values.global.devCleanupID }}"
          command:
            - /bin/bash
            - -c
            - |
              if [ -z "$DELETE_ID" ]; then
                echo "DELETE_ID is not set"
                exit 0
              fi
              echo "DELETE_ID is set"
{{- end }}
